### ISSUE TITLE
setup.py and packages on PyPI

### ISSUE THREAD

**Issue by NotSqrt** [HDFGroup/h5serv#102]
Hi !

I think it would really ease the feedback you ask for on https://support.hdfgroup.org/projects/hdfserver/ if this project and its dependencies were easily installable with pip (requirements correctly declared in setup.py, releases pushed to PyPI, ..).

You also mention a version 0.2.0 on https://support.hdfgroup.org/projects/hdfserver/, but there's no corresponding git tag..

I really want to test this, it seems perfect for my use case !
Thanks !

**Comment by jreadey** [comment]
I've create a setup.py and uploaded an h5serv package to PyPI: https://pypi.python.org/pypi?name=h5serv&version=1.2.0&:action=display.

I've verified on a clean system that doing a pip install of the wheel properly installs all dependent packages.

And if I expand the wheel, I can run the server:

```
$ python app.py --log_file=<log_dir>/h5serv.log --datapath=<data_dir>
```
Where "log_dir" is the full path to a directory for log files and "data_dir" is the full path to the data directory (where the data files will be stored).

I'd like to have an executable script be part of the package, so you could just run say, 'h5serv' to start the server.  But I couldn't get the entry_points part of setup.py to do the right thing.  Any ideas?

**Comment by NotSqrt** [comment]
Nice !

My setup.py usually looks like:

```python
from setuptools import setup

setup(
 ....
    entry_points={
        'console_scripts': [
            'gits = module1.module2:main',  # main is a function in module1/module2.py
        ],
    }
)
```

Hope it helps !
