### ISSUE TITLE
How long does it take to recognize a new file in the data folder?

### ISSUE THREAD

**Issue by ahalota** [HDFGroup/h5serv#119]
I just added a new file to my data folder but it's not appearing in the list of links when I browse through the json output of my server in a web browser.

How long should it take to recognize this?
Am I missing a step?

**Comment by jreadey** [comment]
It should show up in a few seconds.
Does the file have the same extension as the others? And are you sure it is really an HDF5 file?

Try watching the h5serv log output when you copy the file in.  You should some messages from the watchdog timer.

**Comment by ahalota** [comment]
I copied it in via urrlib download in a python script, might that affect
things?

**Comment by jreadey** [comment]
I wouldn't think so.  If you just copy files in, does it work?
Also, restart the server if you haven't recently.

**Comment by ahalota** [comment]
Thanks, searching the long helped me figure out the issue.

I had several similar looking data folders and was placing my new file into the wrong one, the log showed me where it was trying to find the file.
