### ISSUE TITLE
Name of package `server` is too generic

### ISSUE THREAD

**Issue by telamonian** [HDFGroup/h5serv#123]
The Python code in this project is all contained in a package named `server`. This means that if I want to important a component of this package in some other piece of Python code I have to write:

    from server import app

This is so generic that if another person reads my code (or myself in a month or two after I've forgotten writing it) they won't have any idea what `server` actually is. The generic name is also likely to conflict with the name of other packages (ie within a user's `site-packages` directory). 

Ideally, the package itself should also be called something like `h5serv`.

**Comment by jreadey** [comment]
Hi @telamonian:
  That's a good suggestion.  Would you like to submit a PR to change the package name to h5serv?

**Comment by telamonian** [comment]
I'm working on a PR to fix this and a bunch of "infrastructure" (problems with `import` statements, problems with `setup.py`, etc) issues right now. I also fixed the `entry_points` in `setup.py` so that you can start the program just by calling the command `h5serv` wherever.

The stumbling block right now is actually a bunch of the pathing stuff in `app.main()` and `config`. I'll start a PR with what I have so far and post more about the remaining issues there.
