### ISSUE TITLE
getRootUUID() fails on helper.py

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/h5serv#33]
I tested server on EC2 and I got the following error. 

>======================================================================
>ERROR: testGetCompound (__main__.DatasetTypeTest)
>----------------------------------------------------------------------
>Traceback (most recent call last):
>  File "datasettypetest.py", line 59, in testGetCompound
>    root_uuid = helper.getRootUUID(domain)
>  File "/home/ec2-user/h5serv/test/integ/helper.py", line 43, in getRootUUID
>    rsp = requests.get(req, headers=headers)
>  File "/home/ec2-user/anaconda/lib/python2.7/site-packages/requests/api.py", line 65, in get
>    return request('get', url, **kwargs)
>  File "/home/ec2-user/anaconda/lib/python2.7/site-packages/requests/api.py", line 49, in request
>    response = session.request(method=method, url=url, **kwargs)
>  File "/home/ec2-user/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
>    resp = self.send(prep, **send_kwargs)
>  File "/home/ec2-user/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
>    r = adapter.send(request, **kwargs)
>  File "/home/ec2-user/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
>    raise ConnectionError(err, request=request)
> ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))

**Comment by jreadey** [comment]
I can do the request ok in the browser: http://compound.test.data.hdfgroup.org:7253/.   

Do you have the port set correctly?  The EC2 h5serv is running on port 7253.

**Comment by hyoklee** [comment]
I am not sure. I just ran this:

[ec2-user@ip-172-31-15-26 test]$ pwd
/home/ec2-user/h5serv/test
[ec2-user@ip-172-31-15-26 test]$ python testall.py

On Jan 28, 2015, at 3:24 PM, John Readey <notifications@github.com<mailto:notifications@github.com>> wrote:


I can do the request ok in the browser: http://compound.test.data.hdfgroup.org:7253/.

Do you have the port set correctly? The EC2 h5serv is running on port 7253.

**Comment by hyoklee** [comment]
John,

  I think you can improve helper.py to add config.get('domain'):

def getRootUUID(domain):
    req = getEndpoint() + "/"
    headers = {'host': domain+config.get('domain')}

**Comment by jreadey** [comment]
Right, you'll need to tweak the test/integ/config.py settings to hit the right port and domain.

John

**Comment by hyoklee** [comment]
John,

  BTW, what's so special about number 7253?


On Jan 28, 2015, at 4:55 PM, John Readey <notifications@github.com<mailto:notifications@github.com>> wrote:

Right, you'll need to tweak the test/integ/config.py settings to hit the right port and domain.

John

**Comment by jreadey** [comment]
Joe,
 5000 is a common port, so I wanted something that wouldn't conflict with anything else running on the host.

 Also, 7253 is 'H5' in ascii!

John

**Comment by hyoklee** [comment]
Cool!

On Jan 28, 2015, at 5:09 PM, John Readey <notifications@github.com<mailto:notifications@github.com>> wrote:

Joe,
5000 is a common port, so I wanted something that wouldn't conflict with anything else running on the host.

Also, 7253 is 'H5' in ascii!

John

**Comment by hyoklee** [comment]
John,

  Would you please open 8888 port for data.hdfgroup.org<http://data.hdfgroup.org>?

  I'd like to install THREDDS on EC2.

On Jan 28, 2015, at 5:09 PM, John Readey <notifications@github.com<mailto:notifications@github.com>> wrote:

Joe,
5000 is a common port, so I wanted something that wouldn't conflict with anything else running on the host.

Also, 7253 is 'H5' in ascii!

John

**Comment by jreadey** [comment]
Closing as user misunderstanding.
