### ISSUE TITLE
Improve util/h5tojson.py's IOError: Unable to create file.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/h5serv#37]
If directory is not writable, use /tmp for temporary file.
At least, catch IOError and tell user that a directory is not writable for temporary file.

**Comment by jreadey** [comment]
I'm not sure I follow - h5tojson just writes to standard out.  If I do something like this:
python h5tojson.py tall.h5 >myreadonlydir/tall.json
I get a typical shell error:
-bash: myreadonlydir/tall.json: Permission denied

**Comment by hyoklee** [comment]
Make your current working directory readonly. For example, the directory where tall.h5 resides and see what happens.

**Comment by jreadey** [comment]
Fix is out.
Joe - let me know if this works ok in Windows - there are some differences in how tempfiles are handled vs. Mac OS X and Linux.
