### ISSUE TITLE
h5tojson.py can't produce JSON file.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/h5serv#38]
You can get the test file from:

http://www.hdfgroup.uiuc.edu/ftp/pub/outgoing/he5_nc4_augment/augmented/OMI-Aura_L2G-OMCLDO2G_2007m0129_v002-2007m0130t174603.he5

```
python h5tojson.py -d /tmp/OMI-Aura_L2G-OMCLDO2G_2007m0129_v002-2007m0130t174603.he5 
Traceback (most recent call last):
  File "h5tojson.py", line 212, in <module>
    main()
  File "h5tojson.py", line 209, in main
    dumper.dumpFile()    
  File "h5tojson.py", line 175, in dumpFile
    self.dumpDatasets()
  File "h5tojson.py", line 141, in dumpDatasets
    item = self.dumpDataset(uuid)
  File "h5tojson.py", line 127, in dumpDataset
    attributes = self.dumpAttributes('datasets', uuid)
  File "h5tojson.py", line 56, in dumpAttributes
    attr_list = self.db.getAttributeItems(col_name, uuid)
  File "../server/hdf5db.py", line 742, in getAttributeItems
    item = self.getAttributeItemByObj(obj, name, False)
  File "../server/hdf5db.py", line 689, in getAttributeItemByObj
    typeItem = hdf5dtype.getTypeItem(attrObj.dtype)
  File "../server/hdf5dtype.py", line 79, in getTypeItem
    type_info = getTypeElement(dt)
  File "../server/hdf5dtype.py", line 124, in getTypeElement
    type_info['base'] = getBaseType(h5t_check)   
  File "../server/hdf5dtype.py", line 239, in getBaseType
    raise TypeError("unexpected dtype base kind: " + dt.base.kind)
TypeError: unexpected dtype base kind: O
```

**Comment by jreadey** [comment]
This is the problematic attribute:

ATTRIBUTE "DIMENSION_LIST" {
                     DATATYPE  H5T_VLEN { H5T_REFERENCE { H5T_STD_REF_OBJECT }}
                     DATASPACE  SIMPLE { ( 3 ) / ( 3 ) }
                     DATA {
                     (0): (DATASET 96168842 /HDFEOS/GRIDS/CloudFractionAndPressure/nCandidate ),
                     (1): (DATASET 96168570 /HDFEOS/GRIDS/CloudFractionAndPressure/YDim ),
                     (2): (DATASET 96168298 /HDFEOS/GRIDS/CloudFractionAndPressure/XDim )
                     }
                  }

It's using a VLEN data attribute which is not supported in h5serv (because it wasn't working for h5py).
Is this needed for PD?

**Comment by hyoklee** [comment]
Yes.

**Comment by ajelenak-thg** [comment]
> It's using a VLEN data attribute which is not supported in h5serv (because it wasn't working for h5py).

h5py does support dimension scales (H5DS) API. Instead of manually recreating the required dimension scale attributes, let the H5DS API do that work.

**Comment by jreadey** [comment]
That would be a little awkward - h5tojson is just chunking through the attributes and handling each in turn.  If we use the dimension scale api we'd need to do a first pass check with dset.dims and then see what is not picked up as a dimension scale.

I'll check if the vlen data is working now.  Andrew had a fix recently.

**Comment by jreadey** [comment]
I've fixed the REFERENCE in VLEN issue.  h5tojson.py still chokes on aura file, but I don't think it's due to the type issue but the json library trying to dump a GB of data dictionary values.
Is there a requirement that h5tojson support 100 mb hdf5 files for PD?

**Comment by hyoklee** [comment]
John,

  I think –d option should dump data without dataset values and it should not choke.

**Comment by hyoklee** [comment]
Did you commit h5tojson.py? I don't see any change.

**Comment by jreadey** [comment]
?I forgot to push it.  Let me check something though, I want to verify with the h5py style dim scale.


john

________________________________

**Comment by jreadey** [comment]
I've added a fix for obj references that are parts of a compound type (as used in dimscales for the scale to refer back to the dataset).
Be sure your system has a lot of swap space setup to convert the aura file.  The script stores the entire python dictionary for the file representation in memory before writing it out.
