### ISSUE TITLE
h5tojson tool generates invalid attribute "strsize". Change it to "length".

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/h5serv#46]
The hdf5-json documentation says "length" [1].

```
              "name": "Title", 
                    "shape": {
                        "class": "H5S_SCALAR"
                    }, 
                    "type": {
                        "class": "H5T_STRING", 
                        "cset": "H5T_CSET_ASCII", 
                        "order": "H5T_ORDER_NONE", 
                        "strpad": "H5T_STR_NULLPAD", 
                        "strsize": 8
```
[1] http://hdf5-json.readthedocs.org/en/latest/examples/fixed_string_dset.html

**Comment by jreadey** [comment]
Where are you seeing this?  I'm getting "length" for string types in datasets/attributes.  E.g.:
$ python h5tojson.py  ../testfiles/fixed_string_attr.h5

**Comment by hyoklee** [comment]
I'm seeing here:

http://eosdap.hdfgroup.uiuc.edu:8887/thredds/h5json/hdfdap/ftp/pub/outgoing/NASAHDF/TES-Aura_L3-ATM-TEMP_r0000010408_F01_07.he5

The tool was last updated on March 16 so I think it's current. 
[hyoklee@giraffe util]$ ls -l h5tojson.py
-rwxr-xr-x. 1 root root 8055 Mar 16 09:39 h5tojson.py

Did you update the tool and forget to check into Git master since then?

**Comment by hyoklee** [comment]
I updated entire h5serv and it generates "length" now. I'm sorry for the false alarm.
