### ISSUE TITLE
exporth5.py fails with KeyError

### ISSUE THREAD

**Issue by ijjorama** [HDFGroup/h5serv#57]
Hi,
I've just installed the h5serv REST server and wanted to test it from a remote client. Using exportjson.py against tall.h5 works OK. I tried the exporth5.py utility against tall.h5 but came across a Python KeyError - the link object passed to createLinks method doesn't contain a key 'file'. I've added a debugging print statement which prints the link object before it is passed to the createLink method - output is below:

===

python  exporth5.py  -endpoint=130.246.221.115 -port=5000  tall.test.hdf5group.org /tmp/tall.h5domain: tall.test.hdf5group.org
filename: /tmp/tall.h5
file root_uuid: 171adac8-426b-11e5-a76e-facade0000e9
Value of link object: {u'target': u'http://130.246.221.115:5000/groups/17368d0e-426b-11e5-a76e-facade0000e9', u'title': u'newsubdirparent', u'collection': u'groups', u'class': u'H5L_TYPE_HARD', u'href': u'http://130.246.221.115:5000/groups/171b5606-426b-11e5-a76e-facade0000e9/links/newsubdirparent', u'id': u'17368d0e-426b-11e5-a76e-facade0000e9'}
Value of link object: {u'target': u'http://130.246.221.115:5000/?host=enum_dset.test.hdfgroup.org', u'h5path': u'/', u'title': u'enum_dset', u'h5domain': u'enum_dset.test.hdfgroup.org', u'href': u'http://130.246.221.115:5000/groups/171b5606-426b-11e5-a76e-facade0000e9/links/enum_dset', u'class': u'H5L_TYPE_EXTERNAL'}
Traceback (most recent call last):
  File "exporth5.py", line 352, in <module>
    main()
  File "exporth5.py", line 340, in main
    dumper.writeFile(db) 
  File "exporth5.py", line 268, in writeFile
    self.createLinks()      # link it all together
  File "exporth5.py", line 254, in createLinks
    self.createLink(link, group_uuid)
  File "exporth5.py", line 75, in createLink
    link_file = link_obj["file"]
KeyError: 'file'

===

On the second call to createLink, the link object has a 'class' of 'H5L_TYPE_EXTERNAL' and createLink tries to access the link_obj["file"] element, which doesn't exist.

Regards,
Ian Johnson.

**Comment by jreadey** [comment]
Hey,  Looks like I forgot to update this utility when we updated the link schema.  Fix is checked in now.  You'll need to do a "git pull origin master" in the hdf5-json sub-module and then a pull in h5serv to get the updates.  Let me know if this works for you.

**Comment by ijjorama** [comment]
That fix works fine. Job's a good 'un!
