### ISSUE TITLE
h5pyd 'python setup.py install' doesn't seem to install correctly

### ISSUE THREAD

**Issue by ijjorama** [HDFGroup/h5serv#61]
I tried to install h5pyd by running the setup.py script in h5serv/client/h5pyd
This seems to just copy and install the files contained in the h5pyd/h5pyd directory, but not the h5pyd/h5pyd/_hl subdir:

ls /usr/local/lib/python2.7/dist-packages/h5pyd-0.1-py2.7.egg/h5pyd/
hdf5dtype.py  hdf5dtype.pyc  __init__.py  __init__.pyc  version.py  version.pyc

Result is that I can't import the h5pyd client library:
    python -c 'import h5pyd'
    Traceback (most recent call last):
    File "\<string\>", line 1, in \<module\>
    File "/usr/local/lib/python2.7/dist-packages/h5pyd-0.1-py2.7.egg/h5pyd/__init__.py", line 26, in \<module\>
    from ._hl.files import File
     ImportError: No module named _hl.files

Please advise whether I've run the setup step correctly.

**Comment by jreadey** [comment]
@ijjorama - the h5pyd package is experimental at this point, and frankly I've always just did "setup.py develop" so the install package would just point to my dev tree.  Anyway, I've checked changes to add the _hl package.  Let me know if this works for you.

**Comment by ijjorama** [comment]
Thanks - that's fixed it!
