### ISSUE TITLE
h5pyd client library: h5pyd/_hl/dataset.py is missing an import

### ISSUE THREAD

**Issue by ijjorama** [HDFGroup/h5serv#64]
Hi,
I had an exception when trying to run a h5pyd client program:

Traceback (most recent call last):
  File "dist-datasetsize.py", line 80, in <module>
    main()
  File "dist-datasetsize.py", line 75, in main
    (name, dsize, typ, timeperfetch, d.len()/timeperfetch / pow(10, 3) )
  File "/usr/local/lib/python2.7/dist-packages/h5pyd-0.1-py2.7.egg/h5pyd/_hl/dataset.py", line 393, in len
    with phil:
NameError: global name 'phil' is not defined

I found the following import fixed the problem:

*** /usr/local/lib/python2.7/dist-packages/h5pyd-0.1-py2.7.egg/h5pyd/_hl/dataset.py.orig	2015-09-21 12:11:27.413123262 +0100
--- /usr/local/lib/python2.7/dist-packages/h5pyd-0.1-py2.7.egg/h5pyd/_hl/dataset.py	2015-09-21 12:12:21.829125656 +0100
***************
*** 23,28 ****
--- 23,29 ----
  
#from . import base
from .base import HLObject
\+ from .base import phil

Cheers,
Ian Johnson.

**Comment by ijjorama** [comment]
Hi,
Have you had a chance to look into this? The line 'from base import phil' seems to be missing from the latest version of h5pyd/_hl/dataset.py

Cheers,
Ian Johnson.

**Comment by jreadey** [comment]
Sorry about that, this one slipped off the priority stack.
I've put in a fix, let me know if that works for you.

**Comment by ijjorama** [comment]
Hi John,
Thanks, that works a treat.
