### ISSUE TITLE
Windows 7 testall.py failing - testDeleteSubSubDomain, testGetToc, testQuer*s

### ISSUE THREAD

**Issue by ahalota** [HDFGroup/h5serv#71]
never mind.

**Comment by jreadey** [comment]
@ahalota - what was the issue?

**Comment by ahalota** [comment]
I'm just having trouble getting the tests to run clean on an install, I thought that was the hang-up on the tests (I see now it changes directory so that file is not the problem).

I'm failing these tests:
* testDeleteSubSubDomain in roottest.py, returning 500 instead of 200.
* testGetToc in dirtest.py, returning 404 instead of 200
* testQueries, testQuery, testQueryBatch, testQuerySelection, returning 500 instead of 200.

**Comment by jreadey** [comment]
I just did a clean install and test run on a linux host.  What OS are you using?

**Comment by ahalota** [comment]
Windows 7, 64bit.

**Comment by jreadey** [comment]
I'm seeing errors with Windows 7 as well - let me look into it.

**Comment by ahalota** [comment]
I think this might be related to folder permissions somehow. I am running both instances of Anaconda prompt as administrator, but I can see "403 Access is not permitted" for the PUT requests.

**Comment by jreadey** [comment]
It should be fine to run with your user privalages unless you want to use a low port number (see the 'port' and 'ssl_port' values in server/config.py.

**Comment by jreadey** [comment]
I've checked in fixes for the testDeleteSubSubDomain and testGetToc errors.

To re-run, you'll need to do a one-time erase of the hidden data/.toc.h5 file.  From a windows cmd prompt run:

> erase /A:H .toc.h5

in the data directory.

**Comment by jreadey** [comment]
Fixes for acl error and query tests checked in.

I have a clean pass on windows now.  Let me know if these updates work for you.

**Comment by ahalota** [comment]
Same here!
