### ISSUE TITLE
Strings with unlimited length produce error?

### ISSUE THREAD

**Issue by baderas** [HDFGroup/h5serv#77]
Hi,

I am not sure if I do something wrong, but I think there might be an error when using strings with unlimited length.

Using the following datatype:
```
{
"name": "test",
"shape": {
    "class": "H5S_SCALAR"
},
"type": {
    "class": "H5T_COMPOUND",
    "fields": [
            {
            "name": "VALUE1",
            "type": {
                    "base": "H5T_STD_U64BE",
                    "class": "H5T_INTEGER"
                }
            },
            { 
            "name": "VALUE2",
            "type": {
                    "base": "H5T_IEEE_F64BE",
                    "class": "H5T_FLOAT"
                }
            },
            { 
            "name": "VALUE3",
            "shape": {
                    "class": "H5S_SIMPLE",
                    "dims": [4]
            },
            "type": {
                    "class": "H5T_STRING",
                    "charSet": "H5T_CSET_ASCII",
                    "strPad": "H5T_STR_NULLTERM",
                    "length": 5
            }
            }
        ]
}
}
```

and the following dataset where &lt;datatype> is the id of the datatype above:
```
{
"shape": 10,
"type": "<datatype>", 
"maxdims" : 0
}
```

and the following request (put_value.json):
```
{
"start": 0,
"stop": 1,
"value": [ 111111112121,1.1,"a"]
}
```

executed with `curl -v -H "Content-Type: application/json" -X PUT -H "host:hdfgroup.org" --data "@put_value.json" localhost:5000/datasets/<dataset>/value` where &lt;dataset> is the id of the dataset above, everything works fine.

But when I use the same datatype with unlimited strings  (doing every other step accordingly):
```
{
"name": "test",
"shape": {
    "class": "H5S_SCALAR"
},
"type": {
    "class": "H5T_COMPOUND",
    "fields": [
            {
            "name": "VALUE1",
            "type": {
                    "base": "H5T_STD_U64BE",
                    "class": "H5T_INTEGER"
                }
            },
            { 
            "name": "VALUE2",
            "type": {
                    "base": "H5T_IEEE_F64BE",
                    "class": "H5T_FLOAT"
                }
            },
            { 
            "name": "VALUE3",
            "shape": {
                    "class": "H5S_SIMPLE",
                    "dims": [4]
            },
            "type": {
                    "class": "H5T_STRING",
                    "charSet": "H5T_CSET_ASCII",
                    "strPad": "H5T_STR_NULLTERM",
                    "length": "H5T_VARIABLE"
            }
            }
        ]
}
}
```

then I get as response:

```
* upload completely sent off: 55 out of 55 bytes
< HTTP/1.1 500 Internal Server Error
< Date: Mon, 08 Feb 2016 21:34:59 GMT
< Access-Control-Allow-Origin: *
< Content-Type: text/plain
< Content-Length: 448
* Server TornadoServer/3.2.2 is not blacklisted
< Server: TornadoServer/3.2.2
< 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1346, in _when_complete
    callback()
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1367, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "app.py", line 1928, in put
    log.info("IOError: " + str(e.errno) + " " + e.strerror)
TypeError: cannot concatenate 'str' and 'NoneType' objects
* Connection #0 to host localhost left intact
```

**Comment by jreadey** [comment]
I'm now sure that a dataset of this type can be created using h5py (which is what h5serv uses to interface to the hdf5 library).

I've updated this h5py issue: https://github.com/h5py/h5py/issues/581, but it doesn't look hopeful that this can be resolved quickly.  

Can you restructure your application to not use vlen's in a compound type?  Say by having the vlen's in their own dataset.

**Comment by baderas** [comment]
> Can you restructure your application to not use vlen's in a compound type? Say by having the vlen's in their own dataset.

I can use fixed length string, that is not a problem and works as a solution. Or is it not recommended to use strings (fixed length or variable length) in a compound type at all?

**Comment by jreadey** [comment]
If your strings are about the same size, then fixed length strings have some advantages (e.g. more efficient to access, compression is supported).  If not though, you may end up wasting a lot of space, since every element in the array will take up the string length number of bytes regardless of if it used or not.

I made some progress on the h5py issue mentioned above yesterday, I'll see if I can fix the problem with variable length string in compound types.

**Comment by jreadey** [comment]
I think I have a fix for this issue in.  Checkout the test: testPostCompoundArrayVLenStringType in datasettest.py.  The test is using the same type you described.

If you are happy with fixed length strings, you should keep it.  I think they'll be slightly more performant than using variable length strings.

**Comment by jreadey** [comment]
Closing the issue - please reopen if you see any problems with the fix.
