### ISSUE TITLE
Can't use POST from web browser (javascript) to retrieve values by Point selection

### ISSUE THREAD

**Issue by ahalota** [HDFGroup/h5serv#78]
I am trying to extract data by a set of arbitrary points, could be several hundred at once.

I've been using the [Restful HDF5 manual](https://www.hdfgroup.org/pubs/papers/RESTful_HDF5.pdf) as a guide to the server.

 On page 14 of the manual, I see how to grab a simple hyperslab selection. On page 39 I also see a line item `205` for `selection` that shows the option `points` as input to a selection, but no further description of this is in the document. 

I have two questions for you, I would really appreciate your help:

1) Is it possible to use the HDF5 server to make a selection based on a set of input points?
2) If it is, is this as quick or quicker than making several calls for rectangles instead? If the point method is much slower, I can split my selection into rectangles first and use the regular selection method instead.

**Comment by jreadey** [comment]
The Restful HDF5 manual is a good conceptual guide, but it was written before the implementation of h5serv, and some of the specifics have changed.  The h5serv on readthedocs is the place to go for questions about api usage:http://h5serv.readthedocs.org/en/latest/.  

I suspect in most cases point selection will be faster than reading data by values.  Use POST value to submit a set of points and get the values back.  See: http://h5serv.readthedocs.org/en/latest/DatasetOps/POST_Value.html.
Also see the testPost test in h5serv/test/integ/valuetest.py.  
Let me know if you still have questions or run into any issues.

**Comment by ahalota** [comment]
I'm now using POST to request a 2d array of points. In my javascript, my request looks like this:

```
$.post("http://127.0.0.1:5000/datasets/c2b9dc21-d1be-11e5-9e5e-f01faf2b586e/value", 
{host: "GFED_1997.hdfgroup.org"
points: "[[331,181],[332,180],[332,181],[333,173],[333,179]]"});
```
The server gives me a JSON Parser Error: No JSON object could be decoded. I made some edits to the h5server log, and I can see that the following is what the server is receiving in the self.request.body variable (near line 1610, in ValueHandler.post). The values were url encoded (%5B%5D..), I've decoded them here for clarity:

`host=GFED_1997.hdfgroup.org&points=[[331,181],[332,180],[332,181],[333,173],[333,179]]
`

**Am I doing something wrong in formatting my request, or is the server reading it wrong?**

------------

Another thing I noticed is that the server does not properly interpret the post value if an actual array is passed in, rather than a string. I'm not sure if that is expected or not. For example, changing the above request to this:

```
$.post("http://127.0.0.1:5000/datasets/c2b9dc21-d1be-11e5-9e5e-f01faf2b586e/value", 
{host: "GFED_1997.hdfgroup.org"
points: [[331,181],[332,180],[332,181],[333,173],[333,179]]});
```

Gives the following as received by the server:
`host=GFED_1997.hdfgroup.org&points[0][]=331&points[0][]=181&points[1][]=332&points[1][]=180&points[2][]=332&points[2][]=181&points[3][]=333&points[3][]=173&points[4][]=333&points[4][]=179`

**Comment by jreadey** [comment]
The points should be passed in the body of the requests (as an actual array) and not as a query parameter.
I'm not that familiar with the javascript syntax for this, but see if you can get it to follow the pattern in the POST points example in the docs: http://h5serv.readthedocs.org/en/latest/DatasetOps/POST_Value.html.

**Comment by ahalota** [comment]
I am passing them in the body. Of the fields described in the document example, my browser's network tab shows:

Request: 
```
POST /datasets/c2b9dc21-d1be-11e5-9e5e-f01faf2b586e/value HTTP/1.1
Host: 127.0.0.1:5000
Connection: keep-alive
Content-Length: 1604
Cache-Control: max-age=0
Accept: */*
Origin: null
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8
```

Form Data:
```host=GFED_1997.hdfgroup.org&points=[[331,181],[332,180],[332,181],[333,173],[333,179],[333,180],[333,181],[334,172],[334,173],[334,174],[334,178],[334,179],[334,180],[334,181]]```

Response:
```
HTTP/1.1 400 JSON Parser Error: No JSON object could be decoded
Date: Wed, 17 Feb 2016 19:33:05 GMT
Access-Control-Allow-Origin: *
Content-Type: text/plain
Content-Length: 354
Server: TornadoServer/4.3
```

**Comment by ahalota** [comment]
I think the content-type is where I am having trouble actually. I will see if I can get that to say application/json and hopefully that will fix it.

**Comment by jreadey** [comment]
I haven't test with Windows for a bit - I'll do a run this afternoon and see if there are any issues.

**Comment by ahalota** [comment]
I've found the source of the problem, but no solution yet. 

This is what my request looks like when I attempt to change the content-type of data sent to the h5server to json:

![network](https://cloud.githubusercontent.com/assets/15645695/13124112/902452fe-d58d-11e5-92a9-47145a42f3fa.png)

From a web-browser (maybe elsewhere as well), sending an HTTP POST request receives a preflight OPTIONS request when the content-type is changed to application/json. [HTTP access control (CORS)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests). This applies to any cross-origin request, but since h5 server is not a web server, this means that any website requesting data from h5 server will have to be on a different origin, and that can't be avoided.

BUT, the h5server does not allow access-control-method OPTIONS. The line that mentions this in the log is 
`WARNING:tornado.access:405 OPTIONS`
(Browser output: "Response for preflight has invalid HTTP status code 405")

One solution seems to be making an edit to the server setup to allow the OPTIONS method. I'm not sure where that would be within the h5server files though.

**Comment by ahalota** [comment]
It looks like it might also be solved if I can add my webserver to the access-control-allow-origin list in the tornado server. [Stackoverflow: CORS with jQuery and tornado](http://stackoverflow.com/questions/11463688/cross-origin-resource-sharing-cors-with-jquery-and-tornado).

**Comment by jreadey** [comment]
The default config.py on the server should enable cors:
line 33: 'cors_domain': '*'

**Comment by ahalota** [comment]
Looks like that wasn't it. It is indeed allowing CORS, but that still forces the OPTIONS being sent from the web browser.

**Comment by ahalota** [comment]
Found the solution:

app.py needs an options method for various handlers. This will mostly just parse the options and then send it on to the appropriate other method.

I'm going to add one for the ValueHandler that I need and can submit that once it's ready, that can probably be easily adapted for the other handlers.

**Comment by jreadey** [comment]
Cool.  If you can do it in BaseHandler that will take care of everything.

**Comment by ahalota** [comment]
Is there a different place other than self.request.body that the payload request might be stored in? I am able to continue past the OPTIONS call into POST, but it seems to see an empty self.request.body (from the browser, I see that something *is* getting passed in through a payload request, but I can't find it within the app.py handler)

**Comment by jreadey** [comment]
@ahalota: Can you provide a self contained javascript file (that I could run with node.js) or curl script that illustrates the problem?  I can take a look on my end.

**Comment by ahalota** [comment]
Glad you asked! I found a solution while creating a demo file for you. Below is the code I ran (replace the URLS with some for files you have that make sense)

```
<html>
	<head>
		<title>Test POST from Browser</title>
	</head>
	<script>
		function init(){
			var fileUrl = "http://127.0.0.1:5000/datasets/c2b9dc21-d1be-11e5-9e5e-f01faf2b586e/value?host=GFED_1997.hdfgroup.org";
			var payload = {points: [[331,181],[332,180],[332,181],[333,173],[333,179]]};
			
			var xhttp = new XMLHttpRequest();
			
			xhttp.onreadystatechange = function(d){
				if (xhttp.readyState == XMLHttpRequest.DONE){
					console.log(d.target);
					document.getElementById("results").innerHTML = d.target.responseText;					
				}
			}

			xhttp.open("POST", fileUrl, true);			
			xhttp.setRequestHeader("Content-type", "application/json");
			xhttp.send(JSON.stringify(payload));

		}
	</script>
	<body onload="init()">
		<div id="results">
		</div>
	</body>
</html>
```
	
I made the following changes to app.py, added a function to the BaseHandler in line 178:

```
    def options(self): 
        self.set_header('Access-Control-Allow-Headers', 'Content-type,')
```

Important things to note when sending the request is to use JSON.stringify() payload, or else the server will not accept the results as valid JSON.

**Comment by ahalota** [comment]
As a side-note to my original question, now that I have it running, I can see that the hyperslab selection (GET &select) is much (5-10 times) faster than selecting by points. My common example has about 1000 points being selected at once, and it's noticeably slower than selecting a large rectangle. 

For my use case (selecting a polygon over an x-y region), I'm going to set up an algorithm to split my polygon into rectangles and request those instead.

**Comment by jreadey** [comment]
What size rectangle are you using?

**Comment by ahalota** [comment]
Same size. I was comparing setting it up as a hyperslab versus requesting all of the included points.

**Comment by jreadey** [comment]
Right, I met to ask what size was the hyperslab selection?

**Comment by ahalota** [comment]
Two identical areas:
Hyperslab: [412:487,457:524]
Points: Array[4884]

Bigger than I thought actually ....

**Comment by jreadey** [comment]
Right in that case I'd expect the hyperslab selection to be much faster.
If your use case involves a sparse collection of points vs a large hyperslab selection, then the former should perform faster (esp. if the client and server are not on the same machine).

**Comment by ahalota** [comment]
In that case, what do you think would be quicker, given a large polygon (~4000 points), all points inside of it, in a shape that can be split up into let's say 10 different hyperslab selections (=10 calls to the server).

1) Retrieve a bounding rectangle hyperslab, then extract only those points I need (serverside, or userside)?
2) Split my shape into rectangles first, then request several hyperslabs?

I'm leaning towards #1, since I'm assuming the number of calls to the server will be my bottleneck, with a serverside pre-processing step to grab only those points I need and send to the client, unless it's quick enough to iterate the array of points on the client side (I'm not too familiar with javascript efficiency, so maybe it's not as intensive as I suspect).

**Comment by jreadey** [comment]
If you plan to have a server-side component (say a node-js service), that will make doing things that involve a lot of h5serv calls much faster obviously.

If the only service is h5serv, then you'll want to minimize round trips and the amount of data that goes back and forth.  Best approach is to try out the different alternatives and see which works best.  I'd be interested to hear what you find out.

**Comment by jreadey** [comment]
Closing this since it looks like there's nothing needed on my side.  Please update with the results of your experimentation of point selections vs hyperslab.

**Comment by ahalota** [comment]
In case anyone ever runs into this in the future, I went with 1) Retrieve a bounding rectangle hyperslab and extract needed points user-side.

I didn't do any formal time tests, but it went from unacceptably slow to barely noticeable. The only thing to bear in mind is that you will have to 'remap' your resulting points, so to say, since if you asked for [300:320,100:120], you well be returned a ~20x20 array and the indices will have changed.
