### ISSUE TITLE
How to create a non-anonymous dataset?

### ISSUE THREAD

**Issue by baderas** [HDFGroup/h5serv#80]
When using GET Value, I always end up with "Bad Request: query selection is not valid for anonymous datasets".
This comes from https://github.com/HDFGroup/h5serv/blob/master/server/app.py around line 1533:
```python
if 'alias' not in item or len(item['alias']) == 0:
                msg = "Bad Request: query selection is not valid for "
                msg += "anonymous datasets"
                log.info(msg)
                raise HTTPError(400, reason=msg)
```

I am using the setup of https://github.com/HDFGroup/h5serv/issues/77. I tried to put the datatype and  dataset in a group ("linked dataset"), pass a name/alias as parameter etc. Nothing helped, every query I try returns this error.

How can I create a non-anonymous dataset, which query argument is required for POST Dataset?

**Comment by jreadey** [comment]
The non-anonymous requirement is an artifact of the underlying implementation use to support dataset queries (PyTables).  

Use "PUT links" to create a link to the dataset.  See the doc here: http://h5serv.readthedocs.org/en/latest/GroupOps/PUT_Link.html.

The testcase h5serv/test/integ/datasettest.py, testPost, shows how this works.

**Comment by baderas** [comment]
Thx I got it to work now.

It should be mentioned somwhere that H5T_STD_U64BE types can't be used in a query, you get 500 "internal server error" with "NotImplementedError: variable ``Value1`` refers to a 64-bit unsigned integer column, not yet supported in conditions, sorry; please use regular Python selections" in the server logs.
H5T_STD_I64BE however works. THX!

**Comment by jreadey** [comment]
Have you tried H5T_STD_U64LE?  Unless you are running on a really old Mac or some such system, little endian should perform a little better (no need to swap bytes).  And I suspect the big endian types don't get tested as much.

**Comment by baderas** [comment]
H5T_STD_U64LE produces the same error.
