### ISSUE TITLE
Can run server, but tests return Errno 10061: Connection Actively Refused (Firewall issues?)

### ISSUE THREAD

**Issue by ahalota** [HDFGroup/h5serv#82]
About 2 months ago, I was able to run the tests perfectly, as well as the server.

Now, I can run the server, but the server tests fail with "[Errno 10061] No connection could be made because the target machine actively refused it."

I've heard this is commonly a firewall issue, and it's possible something has changed on my machine that I am unaware of. I'm curious as to why the server can be run just fine using server/app.py, but none of the tests can run.

I see that the config files for the two are quite different, and am guessing this may be a source of the issue, but any input you have on possible sources to investigate would be very helpful.

**Comment by jreadey** [comment]
It sounds like a network issue if the connection is being refused.  Can you reach the endpoint in a browser?

Generally it's best to run the server on your desktop and verify that the test all run correctly locally (this is the default configuration in the git repo).  If you seeing errors, it may be best to delete h5serv and hdf5-json directories and do a new git clone.  Note I've just updated some of the package dependencies (e.g. Numpy now needs to be 10.1.4 or later).

Once you have it working on the desktop you can try it on your server, run the tests locally there, and then sort out any connectivity issues accessing remotely.   Note the test script assumes it is running on the same box as the server, but there shouldn't matter to the server code if the client is local or remote.

**Comment by ahalota** [comment]
I've only been running it locally so far.  No trouble reaching the server from my browser, just the tests that are acting up.

I haven't cloned any recent updates to the server, so I'll give that a try and see if it changes anything.

**Comment by jreadey** [comment]
I ran through the test suite on Windows today and discovered some portability issues (related to handling window path names).  These are fixed in the development branch (https://github.com/HDFGroup/h5serv/commit/14d4888216d541d4b87037f90812257ccad2dddb).  If you have time, try running the test test suite (cd h5serv/test, python testall.py) locally with the latest changes and let me know if you encounter any problems.

**Comment by jreadey** [comment]
@ahalota - were you able to resolve the problem?

**Comment by ahalota** [comment]
Haven't had a chance to troubleshoot this again, I believe I have the latest update. It's most likely a strange firewall issue on my end, but I'll post here if I learn anything new.

**Comment by jreadey** [comment]
Ok - closing this.  Re-open if you think it's a problem on this end.
