### ISSUE TITLE
How does the acl/password authentication work?

### ISSUE THREAD

**Issue by ahalota** [HDFGroup/h5serv#97]
I'm having trouble understanding what is described in the documentation for authentication. My goal is to have update/post blocked off for all users, except one special user.

I used setacl.py and can succesfully update the acl for the default (userid 0), which then blocks any anonymous requests from making updates. No problem there, and I was also able revert it back to allowing everyone.

I can also create special settings for any other user, so long as the ID is a number, not a name, using setacl.py. If I use it on a name an error occurs, since in set_acl.py there is a line "int(arg)" which tries to parse the input command line argument into a number. 

I used update_pwd.py to create a new user with password. It works fine. 

I don't understand how or whether these two items are related. My username has characters, but the acl only works with numbers. Are they referring to the same users, or are these two different authentication methods and I should pick one of the two??

I see the actltest.py file and I think I can follow along this way to set up the acl settings for the user I made in update_pwd.py, but what is to prevent an unauthorized user from doing this same thing and just creating a user for themselves that has access?

1) Is it possible to use setacl.py exclusively to set up my users and their access abilities? It should block all unregistered or unknown users from from creating/updating anything, and allow my named user to make edits.

2) How do I ensure an unknown user does not follow the steps in acltest.py to log into my database, create a new user, and make edits?

**Comment by jreadey** [comment]
To address you second question first, the tools in h5serv/util/admin (add_user.py, makepwd_file.py, update_pwd.py, setacl.py, import_file.py) are designed to run on the host running h5serv (i.e. they operate on files directly on don't go through the REST API).  To keep user accounts, and ACL's secure, it is necessary to have system security for the machine it's running on and the data files exposed by h5serv.  I.e. if it is possible for someone to ssh into the machine and acquire write access to these files, that person would be able to subvert any security measures enforced by the REST API.

So in setting up h5serv (esp if security is an important issue), you'll want to think about what user the h5serv process runs under, who would have access to the machine, and would they be able to acquire read and/or write access to the h5serv data files (and password file).

Next for your first question, let's take the (simple case) of one file that I want one suer to have full access to and everyone else to have read access to.

 As an example, I'll ssh into a machine running h5serv, go to the util/admin directory and run update_pwd.py:
```
$ python update_pwd.py
>filename: passwd.h5
>username: None
>password: None
>email: None
username                 userid  state   email                                   ctime               mtime
------------------------------------------------------------------------------------------------------------------------
test_user1               1       b'A'    b'None'                                 2016-01-17 15:57:16 2016-01-17 15:57:16
test_user2               2       b'A'    b'None'                                 2016-01-17 15:57:16 2016-01-17 15:57:16
```

**Comment by ahalota** [comment]
Great, that worked out perfect. 

Only thing I was wondering is how does the password.h5 file link to the one referenced in server/config.py ? My config.py has 'password_file': '../util/admin/passwd.h5' . If I have the password file elsewhere, I assume it won't find it and would act as if there was no password file?

I had to add the -f flag when using update_pwd.py because the default location it searches for is '../server/passwd.h5', which isn't an existing folder. It might make sense to have it either load from config, or at least have the default match the default that's included in config.py

My files are called getacl.py and setacl.py, I think you accidentally referred to them as get_acl.py and set_acl.py in your instructions.

**Comment by jreadey** [comment]
Are you on the develop branch in both locations?  Of course you can just do a git pull to get the latest changes.

From a maintenance point of view the util scripts are a bit problematic since they are not covered by the test scripts.  Please file issues for any problems you come across.

**Comment by jreadey** [comment]
I'm closing this issue - please re-open if you need any clarifications on ACL usage.

**Comment by ghost** [comment]
Am able to set ACL on a specific domain. How can I prevent creation of new domains / allow only 1 user to create these domains?

**Comment by jreadey** [comment]
There's nothing preventing users from creating new domains.  While not as bad as allowing data to be deleted or overwritten, it would be best to patch this up.

Have you come across the .toc.h5 file in the h5serv/data directory?  It maintains a list of all domains (using HDF5 external links).   The logic for the create domain check could go like this:

Get the user's ACL from the .toc.h5 file. if the user has "create" permission, allow the creation of the new domain, otherwise fail.  

So any users who have had an ACL added (with 'create' perms) to the .toc file would be able to create new domains, otherwise not.

How does that sound?  

Could you create a new issue to track this?

**Comment by ghost** [comment]
Great suggestion! I just filed the issue at https://github.com/HDFGroup/h5serv/issues/105

**Comment by jreadey** [comment]
Thanks.  I'll plan to work on it this month.
